/* global window */
// Portfolio content — extracted from Experience.docx and Personality.docx
window.PORTFOLIO = {
  owner: {
    name: "Sanjana Kanchibotla",
    initials: "SK",
    role: "Data Scientist · Product Thinker",
    location: "Toronto, ON",
    email: "sanjanakanchibotla@gmail.com",
    links: {
      github: "https://github.com/sanjxksl",
      linkedin: "https://linkedin.com/in/sanjanaksl",
    },
    tagline: "I find the problems worth solving, then use whatever it takes to solve them.",
  },

  folders: [
    { id: "work", name: "Work", kind: "folder" },
    { id: "projects", name: "Projects", kind: "folder" },
    { id: "competitions", name: "Competitions", kind: "folder" },
    { id: "about", name: "About_Me", kind: "folder" },
  ],

  work: [
    {
      id: "cibc",
      name: "ExamScopeAI",
      type: "EXP",
      date: "Jan 2026,Jun 2026",
      role: "ML Analyst · Rotman MMA Practicum",
      location: "Toronto, Canada",
      kicker: "ML Analyst · CIBC CEEP · AML/ATF Compliance",
      title: "ExamScopeAI: <em>Semantic Search</em> for Compliance Examinations",
      subtitle: "A search and analytics system that makes 12 years of CIBC examination history instantly searchable, cutting exam scoping from hours to minutes.",
      body: [
        { h: "The Problem", p: "CIBC's CEEP team examines how well Lines of Business manage AML, sanctions, and regulatory compliance risk. Before any examination begins, examiners have to scope it: determine which processes and controls to assess, surface prior deficiencies, and understand what has changed since the last review. This scoping was entirely manual. Examiners downloaded reports one at a time, read entire documents to extract a few relevant facts, and reconstructed institutional knowledge from memory and partial notes." },
        { p: "Three things made this harder than it needed to be. AML regulations shift constantly, which means scope from two years ago can be partially obsolete with no easy way to surface what has changed. The exam history lived across two separate document repositories with no central index. And scoping decisions were difficult to document and defend under regulatory scrutiny because there was no clear record of what was reviewed and why." },
        { quote: '"We manually download the previous report, scope document, and testing templates just to figure out what was done last time."' },
        { quote: '"There could be a ton of documents we use just to create a single scope."' },
        { quote: '"I still read the entire prior report because so much changes over time. I cannot risk missing something."' },
        { h: "The System", p: "ExamScopeAI indexes CIBC's full examination history across both source repositories and makes it searchable, filterable, and exportable. An examiner types a query, a Line of Business name, a risk theme, a deficiency type, and receives ranked historical reports with relevance scores, extracted processes and controls, deficiency records with ISSUE IDs, and ratings history across fiscal years. Every result traces back to a source document. There are no generated summaries. In a compliance context, the ability to cite a source is not a convenience, it is the requirement." },
        { h: "How It Works", list: [
          "Document Extraction: a custom Python pipeline using pypdf and pdfplumber to parse 468 examination reports and annual exam planning documents spanning 12 years of inconsistent templates. Extracts report titles, risk ratings, report periods, processes, controls, deficiency titles, and ISSUE IDs. Handles scanned PDFs, legacy formats, and three different cover page layouts. Complete.",
          "Validation and QA: automated checks flag extraction issues including truncated rating values, duplicate tokens, missing fields, and multi-dimensional risk values. A QA report identifies 23 records requiring manual review before vectorisation. Complete.",
          "Databricks Integration: cleaned data moves into Delta tables as the production data layer, replacing local file storage and enabling team-wide access, version control, and scalability beyond the initial corpus. In Progress.",
          "Semantic Vectorisation: each document is embedded using Sentence Transformers (all-MiniLM-L6-v2) into a 384-dimensional vector that captures meaning beyond keyword overlap. Vectors are stored in ChromaDB. The system runs fully offline with no external API calls during search. In Progress.",
          "Search API: a FastAPI backend with cosine similarity ranking, filterable by portfolio, fiscal year, quarter, rating, and source type. Four core endpoints, auto-documented and testable. In Progress.",
          "Examiner UI and Export: a search interface with ranked results, a report detail view with tabs for processes, deficiencies, and ISSUE IDs, and one-click Excel export formatted to paste directly into examination templates. In Progress.",
        ]},
        { h: "My Contribution", p: "I led the technical architecture and built the core data pipeline. When the extraction work stalled, I took it over and processed all 468 documents myself to keep the project on schedule for the June leadership presentation. What I owned: the full extraction pipeline across roughly 2,500 lines of code handling 12 years of inconsistent document formats, the validation and QA layer, the complete system architecture, the vectorisation and search backend, user research interviews with CEEP examiners that shaped the product direction, and the executive presentation to CIBC leadership." },
        { h: "What It Changes for Examiners", list: [
          "Finding relevant precedents takes seconds rather than hours, ranked by relevance to the current exam context rather than by keyword matching.",
          "Extracted process and control lists from prior reports give examiners a consistent baseline, so they can distinguish what is standard across the corpus from what was specific to a single exam.",
          "Every result links to a source document, so inclusion and exclusion decisions are traceable and can be defended under regulatory challenge.",
          "Scoping tables export to Excel in a format that pastes directly into examination templates, removing the need to rebuild them manually.",
          "The annual exam plan is integrated alongside historical ratings, so examiners see the full picture of a Line of Business before they begin.",
        ]},
        { h: "What I Learned", list: [
          "Defensibility matters more than convenience in regulated environments. Every result linking to a source is not a limitation, it is what makes the system usable under scrutiny.",
          "Data quality is the real product. The extraction pipeline took longer than anything else because 12 years of inconsistent document formats required hundreds of edge case handlers. The 95% field-level accuracy was earned through that work, not assumed. Everything downstream depends on getting it right.",
          "User research changes what you build. Without the examiner interviews, we would have built a faster search tool. Those conversations revealed that the core problem was traceability and defensibility, not speed. That single insight changed the entire product direction.",
          "Small architecture decisions compound. Designing the data loading step as an isolated function took an extra ten minutes upfront. It means the Databricks migration takes ten lines of code rather than a full rewrite.",
        ]},
      ],
      tags: ["Python", "Semantic Search", "FastAPI", "Databricks", "AML", "FinTech"],
      metrics: [
        { v: "468", l: "exam reports indexed" },
        { v: "95%", l: "extraction accuracy" },
        { v: "12 yrs", l: "FY2014 to FY2026" },
        { v: "2", l: "source repositories" },
      ],
    },
  ],

  projects: [
    {
      id: "exec-anomaly",
      name: "executive_compensation.sql",
      type: "SQL",
      date: "2026",
      kicker: "Financial Analytics, SQL, Risk Scoring, Visualisation",
      title: "Executive compensation <em>anomaly detection</em>",
      subtitle: "An end-to-end anomaly detection and risk scoring system on 30 years of Compustat data, built to surface structural governance risk rather than raw counts.",
      links: {
        github: "https://github.com/sanjxksl/executive-compensation-anomaly",
        tableau: "https://public.tableau.com/views/ExecutiveCompensationAnomalyDetection/AnomalyTrendsbyYear",
      },
      tableauPath: "ExecutiveCompensationAnomalyDetection/AnomalyTrendsbyYear",
      body: [
        { h: "The Problem", p: "Naive anomaly detection in executive pay is misleading. Large industries like Regional Banks produce high raw anomaly counts simply because they have more firms, not because their governance is worse. Without normalisation, any analysis conflates scale with structural failure." },
        { p: "Raw pay figures without performance context are also meaningless. An executive earning ten times the industry median is anomalous. Whether that anomaly reflects governance failure or justified outperformance requires overlaying revenue, profitability, and Tobin's Q." },
        { h: "The System", p: "A modular SQL architecture that first establishes industry-level baselines, flags anomalies by z-score, enriches flagged records with performance data, and then scores industries on a composite risk metric that normalises for scale. The output is a Tableau dashboard that separates industries by structural risk rather than raw count." },
        { h: "How It Works", list: [
          "Industry Baseline Construction: self-join on Execucomp to compute industry-level median and standard deviation of total compensation by year. This is the reference distribution for all anomaly flagging.",
          "Anomaly Flagging: z-score threshold applied per executive per year, flagging records where compensation deviates beyond the threshold from their industry-year distribution.",
          "Performance Enrichment: flagged records joined to Fundamentals Annual and Total Q to contextualise whether pay anomalies align with performance anomalies or represent unjustified excess.",
          "Composite Risk Scoring: Expected Loss framework adapted from actuarial risk scoring. Anomaly rate multiplied by average severity per industry, normalising for size so a small industry with rare but extreme anomalies scores appropriately high.",
          "Visualisation: four-chart Tableau dashboard covering raw anomaly counts by industry, composite risk scores ranked, severity over time, and anomaly rate trend from 1992 to 2022.",
        ]},
        { h: "Key Findings", p: "Industries with the highest raw counts were not the most structurally problematic once normalised. Forest Products, Brewers, and Industrial Gases ranked highest on composite risk. Systems Software and Industrial REITs had the most extreme individual anomalies despite lower frequency." },
        { p: "The temporal trend was counterintuitive: anomaly count grew from 1992 to 2008 while average severity declined over the same period. Governance reforms appear to have reduced the degree of excess even as the number of anomalous packages increased." },
        { h: "What I Learned", list: [
          "Scale confounds raw counts. The Expected Loss framing separates frequency from severity, which is exactly why actuaries use it for insurance risk rather than just counting claims.",
          "SQL views are underused for analytical modularity. Designing each transformation as a view made it trivial to audit any intermediate step and swap in alternative thresholds without rewriting downstream queries.",
        ]},
      ],
      tags: ["SQL", "Financial Analytics", "Risk Scoring", "Tableau", "WRDS"],
      metrics: [
        { v: "30 yrs", l: "Compustat coverage" },
        { v: "3", l: "Compustat tables joined" },
        { v: "4", l: "Tableau charts" },
      ],
    },
    {
      id: "pead",
      name: "pead_replication.py",
      type: "FIN",
      date: "2026",
      kicker: "Empirical Finance, Asset Pricing, Statistical Modelling, WRDS",
      title: "Post-earnings announcement drift <em>replication</em>",
      subtitle: "Ball and Brown (1968) replicated on 23 years of CRSP and Compustat data, with methodological controls for lookahead bias that most replications miss.",
      links: {
        github: "https://github.com/sanjxksl/PEAD",
      },
      body: [
        { h: "The Problem", p: "PEAD is one of the most replicated anomalies in empirical finance, but replication without clean lookahead controls and proper size-adjustment is not replication, it is a rediscovery of noise. The methodological decisions matter as much as the result." },
        { h: "The System", p: "A full empirical pipeline: earnings surprise construction using rolling volatility, CRSP-Compustat linkage via CCM, size-adjusted abnormal return computation using Fama-French NYSE breakpoints, event-time panel construction, and cross-sectional regressions to test where the drift concentrates." },
        { h: "How It Works", list: [
          "SUE Construction: quarterly earnings surprises standardised by an 8-quarter rolling standard deviation of past surprises. Prior-quarter decile breakpoints applied to avoid any lookahead into the current quarter's distribution.",
          "CRSP-Compustat Linkage: merged via the CCM table on PERMNO and GVKEY identifiers, applying date-range filters to handle link validity windows correctly.",
          "Abnormal Returns: size-adjusted using Fama-French NYSE breakpoints. Cumulative abnormal returns computed across a 12-month post-announcement window for each SUE decile.",
          "Cross-Sectional Regressions: HC1 standard errors to confirm whether PEAD concentrates in small firms and to test for secular attenuation over the 2000 to 2023 period.",
        ]},
        { h: "Key Findings", p: "PEAD concentrates in small firms, consistent with limits-to-arbitrage theory: transaction costs and short-sale constraints prevent arbitrage from closing the gap in small caps. Modest secular attenuation in the top-minus-bottom spread, consistent with algorithmic trading accelerating price discovery over the sample period." },
        { h: "What I Learned", p: "Methodology is the finding. The SUE construction choices, rolling window length, decile assignment timing, size-adjustment benchmark, and standard error correction are not implementation details. Each one changes the result. Replication forces you to understand why those choices exist, not just that they exist." },
      ],
      tags: ["Empirical Finance", "Asset Pricing", "Python", "WRDS", "CRSP"],
      metrics: [
        { v: "23 yrs", l: "2000 to 2023" },
        { v: "10", l: "SUE deciles" },
        { v: "12 mo", l: "post-event window" },
      ],
    },
    {
      id: "esg-returns",
      name: "esg_returns.py",
      type: "FIN",
      date: "2026",
      kicker: "Empirical Finance, ESG Analytics, Regression",
      title: "ESG performance and <em>financial returns</em>",
      subtitle: "Twenty thousand firm-years on whether ESG predicts anything that earnings do not already explain.",
      links: {
        github: "https://github.com/sanjxksl/esg-returns-study",
      },
      body: [
        { h: "The Problem", p: "Most ESG-returns studies either omit industry fixed effects or fail to separate the earnings channel from the ESG channel. Without these controls, any positive ESG-returns correlation is likely absorbing industry composition effects and earnings quality signals rather than pricing ESG directly." },
        { h: "The Study", p: "A co-authored analysis of 20,764 firm-year observations across 3,351 US companies from 2013 to 2023, combining ESG ratings from LSEG Refinitiv with financial data from Compustat and CRSP. I led Part II on the determinants of ESG performance itself, using four OLS models with firm-level controls and Fama-French 48 industry fixed effects." },
        { h: "Key Findings", list: [
          "The positive leverage-ESG association in Part II collapsed entirely once industry fixed effects were included, indicating the raw correlation was an artefact of industry composition rather than a real signal.",
          "R&D intensity reversed sign within industries relative to the unconditional estimate, a textbook Simpson's paradox where looking at the full picture hides what is actually happening within groups.",
          "ESG predicts next-year ROA positively and significantly after controls, but the stock return signal disappears once earnings news enters the model.",
        ]},
        { h: "The Central Finding", p: "The market prices ESG through the earnings channel, not as an independent pricing factor. ESG is not a source of excess return. It is a signal that gets absorbed by what it is actually predicting." },
        { h: "What I Learned", list: [
          "Fixed effects are not a robustness check. They are the test. The leverage-ESG result flipping sign after industry controls is the entire story. Without that step, you publish a spurious finding.",
          "Null results are findings. The disappearance of the return signal once earnings news enters is more informative than a positive coefficient would have been. It tells you the mechanism.",
        ]},
      ],
      tags: ["Empirical Finance", "ESG", "Regression", "WRDS"],
      metrics: [
        { v: "20,764", l: "firm-years analysed" },
        { v: "3,351", l: "US firms" },
        { v: "4", l: "OLS models" },
      ],
    },
    {
      id: "credit-risk",
      name: "credit_risk.py",
      type: "ML",
      date: "2025",
      kicker: "Financial ML, Explainable AI, MLOps, AWS SageMaker",
      title: "Credit risk with <em>counterfactual explanations</em>",
      subtitle: "A production-grade credit risk system combining MLP and XGBoost with DiCE counterfactual explanations, a fairness audit, and a live SageMaker deployment with drift monitoring.",
      links: {
        github: "https://github.com/sanjxksl/credit-risk-counterfactual",
      },
      body: [
        { h: "The Problem", p: "Credit models fail in two directions. First, they achieve high AUC while producing miscalibrated probabilities that are useless for risk pricing. Second, they generate predictions with no explanation, leaving declined applicants with no recourse and lenders with no defensible rationale. There was also a data integrity problem underlying both: high predictive power from a single feature is rarely real signal." },
        { h: "The System", p: "An end-to-end ML pipeline from raw mortgage data through feature audit, model training and calibration, counterfactual explanation generation, fairness evaluation, and deployment as a REST API with live drift monitoring." },
        { h: "How It Works", list: [
          "Feature Audit: systematic audit of all categorical features before modelling. Identified that one variable's high predictive power came from a single bureau category showing a 100% default rate across 15,000 cases, indicating an unobserved loan programme rather than genuine borrower risk. Five such artefact features removed before training.",
          "Model Training: MLP and XGBoost trained on cleaned features, achieving AUC-ROC of 0.901. Platt Scaling applied for probability calibration.",
          "Counterfactual Explanations: DiCE generates the minimum loan structure changes to flip a predicted default to an approval. When no feasible restructuring exists, that is treated as meaningful information: the risk is driven by factors that cannot be changed.",
          "Fairness Audit: disparate impact ratio computed across gender, age, and geography. Result of 1.021 confirms the model passes the 80% rule, with calibration gaps under 1.2% across all demographic groups.",
          "Deployment and Monitoring: FastAPI REST endpoint on AWS SageMaker with a custom Docker container. Evidently monitoring layer with retraining triggers on feature drift or predicted default rate shift beyond defined thresholds.",
        ]},
        { h: "What I Learned", list: [
          "Feature auditing is modelling. The bureau category finding was not a preprocessing step. It was the most important decision in the project. A model trained with that feature would have failed on any new originator programme.",
          "Calibration is separate from discrimination. AUC measures ranking. Calibration measures whether a predicted 20% default probability actually corresponds to a 20% default rate. Platt Scaling closes that gap, but only legitimately when the source of miscalibration is class imbalance, not distribution mismatch.",
          "Counterfactual failures are informative. A DiCE failure does not mean the method broke. It means the applicant's risk is structurally immutable. That is a meaningful and actionable finding.",
        ]},
      ],
      tags: ["PyTorch", "XGBoost", "Explainable AI", "AWS SageMaker", "FinTech"],
      metrics: [
        { v: "0.901", l: "AUC-ROC" },
        { v: "1.021", l: "disparate impact ratio" },
        { v: "148K", l: "mortgage applications" },
      ],
    },
    {
      id: "aesthify",
      name: "aesthify.py",
      type: "CV",
      date: "2025",
      kicker: "Computer Vision, Product Design, Design Research",
      title: "Aesthify, quantifying <em>subjective taste</em>",
      subtitle: "A computer vision pipeline scores interior layouts on 7 design principles, validated against human preferences from 101 participants.",
      links: {
        github: "https://github.com/sanjxksl/Aesthify",
      },
      body: [
        { h: "The Problem", p: "Design criticism is observational and post-hoc. Designers justify decisions in the language of principles, but those principles have never been operationalised into computable scores or systematically tested against what people actually prefer. The result is a field that produces confident claims about aesthetics with no empirical grounding." },
        { h: "The System", p: "A Flask web application that accepts an interior image, runs a YOLOv8 object detection pipeline to extract spatial layout features, computes rule-based scores for 7 design principles, and compares those scores against human preference ratings from a controlled study." },
        { h: "How It Works", list: [
          "Object Detection: YOLOv8 via Roboflow API identifies objects in the image, returning bounding boxes, classes, and spatial positions.",
          "Principle Scoring: rule-based functions translate spatial features into numerical scores for each principle. Symmetry is computed from bilateral object distribution; simplicity from object count and spatial variance.",
          "User Study: 101 participants rated interior images on aesthetic preference across demographic groups including geography and design background.",
          "Correlation Analysis: Pearson correlation between computed scores and participant ratings. Demographic clustering to test whether perception patterns vary by background.",
        ]},
        { h: "What the Study Found", list: [
          "Simplicity correlated most strongly with user preference (r = 0.68).",
          "Symmetry was negatively correlated (r = -0.60). People preferred asymmetric layouts, contrary to the conventional design principle.",
          "Aesthetic judgment varied significantly across demographic groups, validating the premise that a single model cannot capture aesthetic preference.",
        ]},
        { h: "What I Learned", list: [
          "Conventional design principles do not predict preference empirically. Symmetry being negatively correlated is not a failure of the system. It is a finding that the principle, as commonly stated, is context-dependent at best.",
          "User-centric design requires measurement. Designers claiming users prefer symmetry without testing it are doing designer-centric design dressed up as user-centric design. This project was built to surface that gap.",
        ]},
      ],
      tags: ["Computer Vision", "Python", "Flask", "YOLOv8", "Design Research"],
      metrics: [
        { v: "101", l: "study participants" },
        { v: "0.68", l: "simplicity correlation" },
        { v: "7", l: "design principles scored" },
      ],
    },
    {
      id: "evidence-engine",
      name: "evidence_engine.py",
      type: "AI",
      date: "2025",
      kicker: "AI Tooling, Product Management, Cognitive Bias",
      title: "Evidence Engine for <em>product decisions</em>",
      subtitle: "A conversational AI tool that forces product managers to gather and challenge evidence before any scoring begins, with transparent reasoning traces on every verdict.",
      links: {
        github: "https://github.com/sanjxksl/evidence-engine",
      },
      body: [
        { h: "The Problem", p: "Prioritisation frameworks like RICE produce the illusion of rigour. The numbers are precise, but the inputs are not. Reach, Impact, and Effort estimates come from whoever in the room is most senior or most confident, not from systematically gathered evidence. The framework launders bias rather than removing it." },
        { h: "The System", p: "A modular LLM-powered tool built in Streamlit using the Gemini API, with distinct reasoning modes: evidence extractor, synthesiser, hypothesis tester, intent classifier, and output generator. Every verdict exposes its supporting and counter-evidence rather than producing a conclusion without a trace." },
        { h: "How It Works", list: [
          "Input Ingestion: raw research inputs including user interview transcripts, support tickets, analytics exports, and stakeholder notes submitted to the tool.",
          "Intent Classification: LLM-based classifier routes the query to the appropriate reasoning mode: hypothesis testing, pattern identification, confidence assessment, stakeholder reporting, or assumption validation.",
          "Evidence Extraction: evidence extracted and classified into six types: user quotes, behavioural observations, support tickets, analytics data, stakeholder input, and competitor intelligence.",
          "Transparent Reasoning Trace: every verdict surfaces both supporting and counter-evidence. The tool does not return a score. It returns a structured case, and the PM decides.",
          "Persistence: SQLite layer stores extracted evidence sets across sessions so the PM builds an evidence base over time rather than starting from scratch each cycle.",
        ]},
        { h: "What I Learned", list: [
          "The problem is not that PMs lack frameworks. The problem is that evidence gathering upstream of the framework is unstructured and biased. A tool that improves the scoring step without improving the evidence step is optimising the wrong thing.",
          "Transparent reasoning traces are a product decision, not a technical one. Showing counter-evidence alongside supporting evidence forces the user to engage with ambiguity rather than accept a verdict. That design choice came directly from the Kahneman-Tversky literature on confirmation bias, not from what was easiest to build.",
        ]},
      ],
      tags: ["LLM", "Streamlit", "Gemini", "SQLite", "Product Tooling"],
      metrics: [
        { v: "5", l: "query modes" },
        { v: "6", l: "evidence types" },
        { v: "4", l: "PMs interviewed" },
      ],
    },
    {
      id: "us-income",
      name: "us_income.py",
      type: "DL",
      date: "2025",
      kicker: "Coursework, Deep Learning",
      title: "US Census income prediction",
      subtitle: "A reliable neural network on imbalanced data, where the naive approach fails.",
      coursework: true,
      links: {
        github: "https://github.com/sanjxksl/us-income-prediction",
      },
      arch: ["Census Data (90 features)", "Preprocessing Pipeline", "2-Layer Neural Network", "Threshold Optimisation", "Income Prediction"],
      body: [
        { p: "Predict whether a person earns above or below $50K annually from US Census data. The class split is 75/25, and naive models optimised for accuracy will simply predict everyone as low-income and look fine on paper." },
        { h: "Key Preprocessing Decisions", p: "MinMaxScaler normalisation was chosen over the more common StandardScaler after a 2% accuracy improvement was observed. Two engineered capital features were added; more than two decreased performance, a finding that held consistently across cross-validation folds." },
        { h: "Model and Training", p: "A two-hidden-layer neural network trained with 5-fold cross-validation. The classification threshold was optimised from the default 0.5 to 0.70 to reduce false positives, an important adjustment given the class imbalance." },
        { h: "Result", p: "85.62% accuracy, 0.9094 AUC-ROC, competitive with gradient boosting methods while demonstrating neural network applicability to tabular data." },
      ],
      tags: ["Deep Learning", "Keras", "Coursework"],
      metrics: [
        { v: "85.6%", l: "accuracy" },
        { v: "0.91", l: "AUC-ROC" },
        { v: "5-fold", l: "cross-validation" },
      ],
    },
    {
      id: "alumni-career",
      name: "alumni_career.py",
      type: "DS",
      date: "2025",
      kicker: "Coursework, Predictive Analytics",
      title: "Alumni career success prediction",
      subtitle: "Scattered, inconsistent institutional data turned into one analysis-ready view.",
      coursework: true,
      links: {
        github: "https://github.com/sanjxksl/alumni-career-success",
      },
      arch: ["4 Fragmented Datasets", "Merge + Standardise", "Feature Engineering", "Random Forest Models", "CLI Predictor"],
      body: [
        { p: "Predict salary and career outcomes for university alumni given their role and location. The institutional problem is that alumni data lives across fragmented, inconsistent files that can't be used for any analysis as-is." },
        { h: "Data Preparation", p: "Merged four separate alumni datasets with salaries stored in incompatible formats including USD, INR, lakhs per annum, and monthly figures. Built a pipeline to standardise, convert, and unify all records into a single usable dataset." },
        { h: "Models", p: "A Random Forest model for salary prediction, evaluated with MAE and R². A second classifier for binary career success (above or below median salary) with balanced class weights, evaluated across accuracy, AUC-ROC, and precision-recall." },
        { h: "Interface", p: "An interactive command-line tool that predicts salary and career success for any combination of role and country, useful for curriculum planning and outcome reporting." },
      ],
      tags: ["Random Forest", "Python", "Coursework"],
      metrics: [
        { v: "4", l: "datasets merged" },
        { v: "2", l: "prediction models" },
      ],
    },
  ],

  competitions: [
    {
      id: "koru",
      name: "koru_thirdplace.md",
      type: "CASE",
      date: "Nov 2025",
      kicker: "Finalist, Koru Problem Hunt",
      title: "Koru Problem Hunt, <em>ThirdPlace</em>",
      subtitle: "A credit-based dual-sided marketplace for hobby discovery, designed from primary research across 79 survey respondents and 8 user interviews.",
      body: [
        { h: "The Problem", p: "Hobby participation has a structural supply-demand mismatch. Studios carry 40 to 60% empty capacity while hobbyists report three consistent barriers: cost (82%), scheduling (84%), and discovery (90%). No existing platform addresses all three simultaneously while giving studios acceptable economics. ClassPass validated the marketplace model but serves fitness only and charges commission structures studios find extractive." },
        { h: "Research", p: "A mixed-methods study combining a quantitative survey (79% aged 18 to 24, equal gender split) and eight in-depth interviews across hobbyists and studio owners. The survey quantified the three barriers. The interviews revealed what studios actually cared about: commission structure, trial-to-member conversion, booking automation, and predictable revenue. Those two data sources shaped everything downstream." },
        { h: "Segmentation", p: "The hobbyist market split into two profiles: Explorers who prioritise variety and schedule flexibility, and Connectors who prioritise community and reducing upfront commitment. Connectors were recommended as the initial target segment based on higher retention potential and lower churn risk." },
        { h: "The Product", p: "ThirdPlace is a dual-sided social marketplace. Hobbyists discover, book, and attend classes through a consolidated feed with group booking and progress tracking. Studios get automated bookings, dynamic pricing to fill off-peak slots, and a fixed transparent commission below Groupon's 50%. Three tiered credit plans at 8, 16, and 32 credits per month with rollover, designed to reduce the upfront commitment that blocked the Connectors segment." },
        { h: "Hypothesis Register", p: "A structured assumption log built across desirability, feasibility, and viability. Each assumption assigned a risk level and a specific experiment design. The register distinguishes between what we know, what we believe, and what we are betting on, which are three different epistemic states that require different responses." },
        { h: "Market Sizing", p: "TAM $45B+, SAM $3.6B, SOM $9 to 15M over three years. 8 competitors analysed." },
        { h: "What I Learned", list: [
          "The friction trinity (cost, scheduling, discovery) only emerged because the research was structured to surface dominant patterns, not to confirm a hypothesis. If the survey had led with solution concepts, it would have anchored respondents and buried the real barriers.",
          "Hypothesis registers prevent premature conviction. Mapping each assumption to a risk level and experiment design forces you to distinguish between what you know and what you are betting on.",
        ]},
      ],
      tags: ["Product Strategy", "Mixed-Methods Research", "Consumer Tech", "Market Design"],
      metrics: [
        { v: "8", l: "user interviews" },
        { v: "51%", l: "avg studio utilisation" },
        { v: "$45B+", l: "TAM" },
      ],
    },
    {
      id: "mma",
      name: "mma_datathon.md",
      type: "CASE",
      date: "Jan 2026",
      kicker: "1st place, Rotman MMA Datathon",
      title: "Rotman MMA Datathon",
      subtitle: "Causal inference on 6,865 hours of web traffic to isolate true paid search impact, identifying a $75-90K reallocation from a loss-making market to a 35% ROI one.",
      body: [
        { h: "Outcome", p: "First place out of all participating teams, Rotman MMA Datathon, January 2026." },
        { h: "The Problem", p: "A retail brand operating across Canada and the US wanted to evaluate whether its paid search campaigns were actually driving traffic, or whether the traffic would have come anyway. Paid search attribution using naive correlation conflates organic lift with paid impact. A brand with strong organic presence will show high traffic correlated with campaign spend simply because both rise together, not because the campaign caused the traffic." },
        { h: "The Method", p: "Causal inference methodology applied to 6,865 hours of web traffic data to separate paid search impact from the organic baseline. Quantified ROI by market after removing the organic component. Separating what the campaign caused from what was already happening is where most analyses of this type go wrong." },
        { h: "The Findings", p: "35% positive ROI in US markets. Loss-making spend in Canada. Recommendation: reallocate $75,000 to $90,000 in paid search budget from Canada to the US. Specific enough to act on immediately." },
        { h: "What I Learned", p: "The business value of causal inference is not the method. It is that it prevents the wrong decision. A correlation-based analysis of this dataset would have shown Canada as merely lower-performing and recommended incremental reallocation. The causal analysis showed it was loss-making and recommended redirecting the full budget. The practical difference between those two findings is $75 to 90K." },
      ],
      tags: ["Causal Inference", "Marketing Analytics", "Python"],
      metrics: [
        { v: "1st", l: "of all teams" },
        { v: "+35%", l: "US ROI" },
        { v: "$75-90K", l: "budget reallocation" },
      ],
    },
    {
      id: "rdc",
      name: "rdc_compass.md",
      type: "CASE",
      date: "Mar 2026",
      kicker: "Finalist (top 7 of 43), Rotman Design Challenge",
      title: "Rotman Design Challenge, <em>Compass</em>",
      subtitle: "An LLM agent embedded in Manulife's app to close the health-wealth gap, reaching top 7 of 43 teams by reframing the problem as navigability failure rather than product failure.",
      body: [
        { h: "Outcome", p: "Finalist, top 7 of 43 teams, Rotman Design Challenge 2026. Designed for Manulife." },
        { h: "The Problem", p: "Manulife's insurance products were not the failure. The interface through which users were supposed to understand and access those products was. 73% of users left benefits unused because they could not navigate their own coverage. The product worked. The experience around it did not. That distinction changed everything about what the solution needed to be." },
        { h: "Research", p: "Seven empathy interviews and 38 survey responses revealed a compounding problem: people who cannot access their benefits incur out-of-pocket costs that add up over time. Three failure modes emerged: users do not know what they have, cannot find it when they need it, and are not reminded at the moments it matters most." },
        { h: "The Product", p: "Compass is a three-layer LLM agent embedded in the Manulife app. A conversational interface for natural language coverage queries. A smart retrieval layer trained on domain-specific insurance data. An event-trigger engine that proactively surfaces relevant coverage at life signals: job change, new dependent, policy renewal." },
        { p: "The proactive trigger layer is the differentiating decision. A reactive chat interface answers questions. A proactive trigger engine surfaces information users did not know to ask for, which is exactly the failure mode the research uncovered." },
        { h: "Validation", list: [
          "87% of users said they would use Compass to find unused benefits.",
          "79% said they would use it to understand their coverage.",
          "62% rated it 7 to 10 out of 10 for usefulness.",
          "62% said it would change their view of Manulife.",
        ]},
        { h: "What I Learned", list: [
          "Navigability failure is a different problem from product failure. The instinct in most design challenges is to redesign the product. The research pointed to the interface, not the product, which changed the entire design direction.",
          "Validation numbers matter more than enthusiasm. The adoption figures are meaningful because they come from real users testing a prototype, not from asking people whether an idea sounds good in the abstract.",
        ]},
      ],
      tags: ["FinTech", "Product Design", "LLM Architecture", "User Research"],
      metrics: [
        { v: "73%", l: "benefits unused" },
        { v: "87%", l: "would adopt" },
        { v: "7/43", l: "finalists" },
      ],
    },
  ],

  learning: [
    { hash: "9e3f2a7", date: "2026·Q2", branch: "JOB SEARCH",
      msg: "Looking for full-time roles — open to 2026 start",
      desc: "MMA practicum wraps in June. Actively interviewing for financial analyst and data science roles in finance and fintech. Looking for teams where deep problem-solving and shipping production systems both matter. LinkedIn and email links are in the dock — reach out anytime.",
      current: true, head: true },
    { hash: "f2c8a91", date: "2026·Q2", branch: "EXAMSCOPE / CIBC",
      msg: "Back at CIBC: final 8 weeks on ExamScopeAI",
      desc: "Returned to the CEEP team for the final stretch of the MMA practicum. Completing the Databricks migration, semantic search layer, and examiner UI ahead of the June leadership presentation. The goal is a system that actually works in the hands of real examiners, not just one that could.",
      current: true },
    { hash: "a1f9d02", date: "2026·Q2", branch: "QUANT FINANCE",
      msg: "Options pricing and asset pricing theory",
      desc: "Working through quantitative finance: options, derivatives, and Black-Scholes. Building the theoretical layer underneath the empirical work done in PEAD and ESG." },
    { hash: "b3c1e77", date: "2026·Q2", branch: "MLOPS",
      msg: "Hardening the credit risk model for production",
      desc: "Revisiting the credit risk counterfactual project from 2025. Hardening the inference pipeline, deployment architecture, and Evidently monitoring layer to production standard on SageMaker." },
    { hash: "7a2c19f", date: "2026·Q2", branch: "PRODUCT",
      msg: "Compass,LLM agent for Manulife (RDC finals)",
      desc: "Three-layer architecture with event triggers on life signals. The health-wealth feedback loop is real and measurable. Top 7 of 43 teams, Rotman Design Challenge 2026." },
    { hash: "d8a04bc", date: "2026·Q1", branch: "EMPIRICAL FINANCE",
      msg: "PEAD replication and ESG returns study",
      desc: "Ball and Brown (1968) on CRSP/Compustat. Then co-authored an ESG study across 20,764 firm-years. The return signal collapses once earnings news enters the model. The market prices ESG through fundamentals." },
    { hash: "e4f1b03", date: "2026·Q1", branch: "RAG / LLM",
      msg: "CIBC: embedded fieldwork then built ExamScopeAI",
      desc: "Two weeks of ethnographic observation before any architecture decision. Built the extraction pipeline across 468 documents, the semantic search layer, and the Databricks roadmap. The scoping problem was a data quality and traceability problem, not a search problem." },
    { hash: "c9a7d51", date: "2026·Q1", branch: "CAUSAL INFERENCE",
      msg: "1st place,MMA Datathon",
      desc: "Causal inference on paid-search web traffic. Learned to separate signal from correlation before recommending a $75-90K spend shift across Canada and the US markets." },
  ],

  gallery: [
    'Celebrating our contribution to Rotman as Ambassadors',
    'Presenting at the Rotman Datathon 2026 finals',
    'Orientation for Rotman\'s Master of Management Analytics',
    'Presenting at the Manulife RDC Case Competition finals',
    'First place at the Datathon Prize Ceremony',
    'Presenting at the Koru Case Competition finals',
    'Design for Future workshop with students from across North America',
    'Showcasing our work at CIBC to the Rotman panel',
  ],

  personality: {
    quote: "I cannot engage with anything at surface level. I need to understand the full system before I trust myself to say or build anything.",
    paragraphs: [
      "What genuinely excites me is problem solving. I love playing with data, building models, testing hypotheses, and seeing where the conclusions land.",
      "Through engineering, product design, and now analytics at Rotman, I have deliberately built a toolkit — user empathy, statistical modelling, ML, financial data analysis — because I want to be able to solve these kinds of problems. Especially the ones where the deeper you go, the stronger the signal gets. And, that is where my passion lives.",
      "Apart from work, I love to write and I have been a dancer. Fun Fact: The first time I performed on stage was when I was 5. I love Linkin Park and I listen to a lot of Indian niche r&b and hip hop artists. I tend to always find new hobbies to keep life exciting and the most recent one is baking!",
    ],
  },

  now: {
    updated: "this week",
    reading: [
      { title: "Inspired", author: "Marty Cagan", note: "want to properly understand the product function." },
      { title: "The Ballad of Never After", author: "Stephanie Garber", note: "missed a good old fantasy romance." },
      { title: "The Alchemist", author: "Paulo Coelho", note: "i think a lot. this one always has something for me." },
    ],
    studying: [
      { title: "MLOps", checked: false, items: ["hardening the credit risk inference pipeline", "SageMaker deployment patterns", "Evidently drift monitoring"] },
      { title: "Databricks + cloud architecture", checked: false, items: ["Delta Lake and medallion architecture", "cloud-native ETL pipelines", "production data engineering at CIBC"] },
      { title: "quant finance", checked: true,  items: ["options pricing and payoff structures", "Black-Scholes model and its assumptions", "derivatives pricing"] },
    ],
  },


  education: [
    { year: "2026", school: "University of Toronto", program: "Rotman School of Management,Master of Management Analytics" },
    { year: "2025", school: "IIIT Design & Manufacturing Kancheepuram", program: "B.Tech, Mechanical Engineering · Minor in Product Design" },
  ],

  achievements: [
    "1st Place,Koru Problem Hunt, 2025",
    "1st Place,Rotman MMA Datathon, 2026",
    "Finals (Top 7 / 43),Rotman Design Challenge, 2026",
    "Founded Alumni Association & Alumni Office at IIITDM (1,270+ records, 350 to 550 attendees)",
    "AWS ML Engineer Associate,in progress",
  ],
};
